# Staging environment values
springProfiles: "staging"

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

envs:
  PORT: "3000"
  MANAGEMENT_PORT: "8081"
  QUEUE_MAX_SIZE: "250"
  WHATSAPP_VERIFY_SIGNATURE: "true"

redis:
  enabled: true
  auth:
    enabled: true
