apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-secrets
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
